{% set name = "asgiref" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60c783a7994246b2e710aa2f0a2f7fcfacf156cffc7b50f7074bfd97c9046db3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - async_timeout >=2.0,<4.0

test:
  imports:
    - asgiref

about:
  home: https://github.com/django/asgiref
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ASGI in-memory channel layer'
  doc_url: https://asgi.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
