{% set name = "asgiref" %}
{% set version = "3.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 566126b4cbf190c315121965253ecb2159499197ff4afd686e0921f4dd987999

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - async_timeout >=2.0,<4.0

test:
  imports:
    - asgiref

about:
  home: https://github.com/django/asgiref
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ASGI in-memory channel layer'
  doc_url: https://asgi.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
