{% set name = "asgiref" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57ed0d07634a23bebfa1b02a1aa05eba09c37aab3fc93893e4039e7bc2d96d9e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - asgiref

about:
  home: https://github.com/django/asgiref
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ASGI in-memory channel layer'
  doc_url: https://asgi.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
