{% set name = "asgiref" %}
{% set version = "3.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 865b7ccce5a6e815607b08d9059fe9c058cd75c77f896f5e0b74ff6c1ba81818

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - asgiref

about:
  home: https://github.com/django/asgiref
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ASGI in-memory channel layer'
  doc_url: https://asgi.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
