{% set name = "asgiref" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c343bd80a0bec947a9860adb4c432ffa7db769836c64238fc34bdc3fec84d590
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  skip: True # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing_extensions >=4

test:
  imports:
    - asgiref
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/django/asgiref
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ASGI in-memory channel layer
  description: |
    ASGI is a standard for Python asynchronous web apps and servers
    to communicate with each other, and positioned as an asynchronous
    successor to WSGI.
  doc_url: https://asgi.readthedocs.io/
  dev_url: https://github.com/django/asgiref

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
