travis:
  secure:
    BINSTAR_TOKEN: Yfx6zBUeTkOpjRSDieZADPykaVkEdkX6w3DbQayEl19WGiHy9U/6pQ+hbN9db1uK+MYDfS9q6A3VbEPWwTgJ2Elhb9DLhZGU+0WJ9arqZPsPYsutxIf9JzX2CnXCnxRQaryGphLIky+LPYGp8FT+bKOMWMxTbJWtISQ2iW6RDB5kIiGT6RmtWWcrMtaNxkYl5QDXPSfRcyyn7BR0r//FpiwVF/UfLDFklep0j9nuyjEgyPL5ZI5StiiczTIR61BDrVkCS2khf6SJfR9eGWv86BL1zdsHT2Vbwg3LJ+DJ4qzi6t5oHTAILx7okv0l/CGoCOGadl1VmnGRYgggTYn2gY/8Djyyg3IkEJaA7LQaDsPLgtVxsORVXMLr/QSvHWhL4QGQCVRfogG0F1E1yRkBJK14AVCGMwAszCkuSU1LqdJuAwLcLAuP+cHhdx+jUpZlZ5cunkGgiejYjBH4JGbyoZeJDTzwipc1v1eA/hueNKZH8gi9vrO0OxV8BX355TNTGuj2Hl5e5/zbro5sFOE1KMBlYzQsQ7KYImc2p1RECdlR2nf8SMrQkxK1juk1jT/Isy5dYkpwOXH96xqINoOnF/QXVcY7pyDILBPP2BUMvvdoA3KF1x0GWPFkapGuoC9FJUFZ+Ej7qeqoC9/jjGw/fAzR3VzjrR/P1Sy/bI98Ttw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
